version: '2'
services:
  app:
    build:
      context: .

  validate-ex:
    extends: app
    volumes:
      - ./tests/schemas:/schemas/
      - ./tests/configs:/configs/
    command:  ["--help"]   # ["--verbose" "<config_file>", "<schema_file>"] 