version: '2'
services:
  app:
    build:
      context: .
      args:
        SCHEMA_DIR: ./tests/schemas/
        CONFIG_DIR: ./tests/configs/
  validate-ex:
    extends: app
    volumes:
      - ./tests/schemas:/schemas/
      - ./tests/configs:/configs/
    command:  ["--help"]   # ["--verbose" "<config_file>", "<schema_file>"] 